#!/bin/bash

source "/opt/loxberry/config/plugins/mirobot2lox/mi.cfg"
LOGFILE="/opt/loxberry/log/plugins/mirobot2lox/mirobot2lox.log"

socat - udp4-listen:$UDP_PORT,reuseaddr,fork | while read COMMAND
do
	D=`date "+%b %d %H:%M:%S"`
	if [ "$COMMAND" = "R1_MI_START" ]; then 
	sudo mirobo --ip $R1_MI_ROBO_IP --token $R1_MI_ROBO_TOKEN start
	echo "R1_MI_START"
	echo "$D Robot 1 UDP Start" >> $LOGFILE
	fi
    if [ "$COMMAND" = "R1_MI_PAUSE" ]; then 
	sudo mirobo --ip $R1_MI_ROBO_IP --token $R1_MI_ROBO_TOKEN pause
	echo "R1_MI_PAUSE"
	echo "$D Robot 1 UDP Pause" >> $LOGFILE
	fi
    
	if [ "$COMMAND" = "R1_MI_DOCK" ]; then 
	sudo mirobo --ip $R1_MI_ROBO_IP --token $R1_MI_ROBO_TOKEN home
	echo "MI_DOCK"
	echo "$D Robot 1 UDP Dock" >> $LOGFILE
	fi
	
	if [ "$COMMAND" = "R1_MI_FIND_ME" ]; then 
	sudo mirobo --ip $R1_MI_ROBO_IP --token $R1_MI_ROBO_TOKEN raw_command find_me
	echo "$D Robot 1 UDP Find Me" >> $LOGFILE
	fi
	
	if [ "$COMMAND" = "R1_MI_DND_ON" ]; then 
	sudo mirobo --ip $R1_MI_ROBO_IP --token $R1_MI_ROBO_TOKEN dnd on 12 0 11 59
	echo "$D Robot 1 UDP DND on" >> $LOGFILE
	fi
	if [ "$COMMAND" = "R1_MI_DND_OFF" ]; then 
	sudo mirobo --ip $R1_MI_ROBO_IP --token $R1_MI_ROBO_TOKEN dnd off
	echo "$D Robot 1 UDP DND off" >> $LOGFILE
	fi
	
	if [ "$COMMAND" = "R1_MI_FAN_Q" ]; then
	sudo mirobo --ip $R1_MI_ROBO_IP --token $R1_MI_ROBO_TOKEN fanspeed 38
	echo "$D Robot 1 UDP Fanspeed Quiet (38)" >> $LOGFILE
	elif [ "$COMMAND" = "R1_MI_FAN_B" ]; then
	sudo mirobo --ip $R1_MI_ROBO_IP --token $R1_MI_ROBO_TOKEN fanspeed 60
	echo "$D Robot 1 UDP Fanspeed Balanced (60)" >> $LOGFILE
	elif [ "$COMMAND" = "R1_MI_FAN_T" ]; then
	sudo mirobo --ip $R1_MI_ROBO_IP --token $R1_MI_ROBO_TOKEN fanspeed 77
	echo "$D Robot 1 UDP Fanspeed Turbo (77)" >> $LOGFILE
	elif [ "$COMMAND" = "R1_MI_FAN_F" ]; then
	sudo mirobo --ip $R1_MI_ROBO_IP --token $R1_MI_ROBO_TOKEN fanspeed 90
	echo "$D Robot 1 UDP Fanspeed Full (90)" >> $LOGFILE
	fi
	
	
		if [ "$COMMAND" = "R2_MI_START" ]; then 
	sudo mirobo --ip $R2_MI_ROBO_IP --token $R2_MI_ROBO_TOKEN start
	echo "R2_MI_START"
	echo "$D Robot 2 UDP Start" >> $LOGFILE
	fi
    if [ "$COMMAND" = "R2_MI_PAUSE" ]; then 
	sudo mirobo --ip $R2_MI_ROBO_IP --token $R2_MI_ROBO_TOKEN pause
	echo "R2_MI_PAUSE"
	echo "$D Robot 2 UDP Pause" >> $LOGFILE
	fi
    
	if [ "$COMMAND" = "R2_MI_DOCK" ]; then 
	sudo mirobo --ip $R2_MI_ROBO_IP --token $R2_MI_ROBO_TOKEN home
	echo "MI_DOCK"
	echo "$D Robot 2 UDP Dock" >> $LOGFILE
	fi
	
	if [ "$COMMAND" = "R2_MI_FIND_ME" ]; then 
	sudo mirobo --ip $R2_MI_ROBO_IP --token $R2_MI_ROBO_TOKEN raw_command find_me
	echo "$D Robot 2 UDP Find Me" >> $LOGFILE
	fi
	
	if [ "$COMMAND" = "R2_MI_DND_ON" ]; then 
	sudo mirobo --ip $R2_MI_ROBO_IP --token $R2_MI_ROBO_TOKEN dnd on 12 0 11 59
	echo "$D Robot 2 UDP DND on" >> $LOGFILE
	fi
	if [ "$COMMAND" = "R2_MI_DND_OFF" ]; then 
	sudo mirobo --ip $R2_MI_ROBO_IP --token $R2_MI_ROBO_TOKEN dnd off
	echo "$D Robot 2 UDP DND off" >> $LOGFILE
	fi
	
	if [ "$COMMAND" = "R2_MI_FAN_Q" ]; then
	sudo mirobo --ip $R2_MI_ROBO_IP --token $R2_MI_ROBO_TOKEN fanspeed 38
	echo "$D Robot 2 UDP Fanspeed Quiet (38)" >> $LOGFILE
	elif [ "$COMMAND" = "R2_MI_FAN_B" ]; then
	sudo mirobo --ip $R2_MI_ROBO_IP --token $R2_MI_ROBO_TOKEN fanspeed 60
	echo "$D Robot 2 UDP Fanspeed Balanced (60)" >> $LOGFILE
	elif [ "$COMMAND" = "R2_MI_FAN_T" ]; then
	sudo mirobo --ip $R2_MI_ROBO_IP --token $R2_MI_ROBO_TOKEN fanspeed 77
	echo "$D Robot 2 UDP Fanspeed Turbo (77)" >> $LOGFILE
	elif [ "$COMMAND" = "R2_MI_FAN_F" ]; then
	sudo mirobo --ip $R2_MI_ROBO_IP --token $R2_MI_ROBO_TOKEN fanspeed 90
	echo "$D Robot 2 UDP Fanspeed Full (90)" >> $LOGFILE
	fi
	
	if [ "$COMMAND" = "R3_MI_START" ]; then 
	sudo mirobo --ip $R3_MI_ROBO_IP --token $R3_MI_ROBO_TOKEN start
	echo "R3_MI_START"
	echo "$D Robot 3 UDP Start" >> $LOGFILE
	fi
    if [ "$COMMAND" = "R3_MI_PAUSE" ]; then 
	sudo mirobo --ip $R3_MI_ROBO_IP --token $R3_MI_ROBO_TOKEN pause
	echo "R3_MI_PAUSE"
	echo "$D Robot 3 UDP Pause" >> $LOGFILE
	fi
    
	if [ "$COMMAND" = "R3_MI_DOCK" ]; then 
	sudo mirobo --ip $R3_MI_ROBO_IP --token $R3_MI_ROBO_TOKEN home
	echo "MI_DOCK"
	echo "$D Robot 3 UDP Dock" >> $LOGFILE
	fi
	
	if [ "$COMMAND" = "R3_MI_FIND_ME" ]; then 
	sudo mirobo --ip $R3_MI_ROBO_IP --token $R3_MI_ROBO_TOKEN raw_command find_me
	echo "$D Robot 3 UDP Find Me" >> $LOGFILE
	fi
	
	if [ "$COMMAND" = "R3_MI_DND_ON" ]; then 
	sudo mirobo --ip $R3_MI_ROBO_IP --token $R3_MI_ROBO_TOKEN dnd on 12 0 11 59
	echo "$D Robot 3 UDP DND on" >> $LOGFILE
	fi
	if [ "$COMMAND" = "R3_MI_DND_OFF" ]; then 
	sudo mirobo --ip $R3_MI_ROBO_IP --token $R3_MI_ROBO_TOKEN dnd off
	echo "$D Robot 3 UDP DND off" >> $LOGFILE
	fi
	
	if [ "$COMMAND" = "R3_MI_FAN_Q" ]; then
	sudo mirobo --ip $R3_MI_ROBO_IP --token $R3_MI_ROBO_TOKEN fanspeed 38
	echo "$D Robot 3 UDP Fanspeed Quiet (38)" >> $LOGFILE
	elif [ "$COMMAND" = "R3_MI_FAN_B" ]; then
	sudo mirobo --ip $R3_MI_ROBO_IP --token $R3_MI_ROBO_TOKEN fanspeed 60
	echo "$D Robot 3 UDP Fanspeed Balanced (60)" >> $LOGFILE
	elif [ "$COMMAND" = "R3_MI_FAN_T" ]; then
	sudo mirobo --ip $R3_MI_ROBO_IP --token $R3_MI_ROBO_TOKEN fanspeed 77
	echo "$D Robot 3 UDP Fanspeed Turbo (77)" >> $LOGFILE
	elif [ "$COMMAND" = "R3_MI_FAN_F" ]; then
	sudo mirobo --ip $R3_MI_ROBO_IP --token $R3_MI_ROBO_TOKEN fanspeed 90
	echo "$D Robot 3 UDP Fanspeed Full (90)" >> $LOGFILE
	fi
	
	if [ "$COMMAND" = "MI2LOX_RESET" ]; then 
	sudo service mirobo2lox stop
	sleep 1
	sudo service mirobo2lox start
	echo "$D Service mirobo2lox UDP Restart" >> $LOGFILE
	fi
done
